server:
  port: 8083

spring:
  application:
    name: analyzer
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  group-id:
    action: ${KAFKA_GROUP_ID_ACTION:analyzer-action-group}
    similarity: ${KAFKA_GROUP_ID_SIMILARITY:analyzer-similarity-group}
  auto-commit: ${KAFKA_AUTO_COMMIT:true}