server:
  port: 8083

spring:
  application:
    name: analyzer
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    enabled: false

kafka:
  enabled: false

grpc:
  server:
    port: 9091
  client:
    GLOBAL:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      negotiationType: PLAINTEXT

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.boot: INFO