spring:
  application:
    name: collector
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

kafka:
  enabled: false
  bootstrap-servers:
  topic: user-actions

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.cloud: DEBUG